# Change these first
owner: ccp-eva # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: Max Planck Institute for Evolutionary Anthropology
    url: https://www.eva.mpg.de/index/
  - name: Kinder schaffen Wissen
    url: https://kinderschaffenwissen.eva.mpg.de/
  - name: OpenEvo
    url: https://openevo.eva.mpg.de/
  - name: OpenEvo Learning Hub
    url: https://openevo-learninghub.eva.mpg.de/
  - name: Gaze Following Task
    url: https://ccp-odc.eva.mpg.de/gafo-demo/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime-monitor
  logoUrl: https://raw.githubusercontent.com/ccp-eva/ccp-favicon/main/res/ccp-orb-unminified.svg
  name: CCP Service Monitor
  introTitle: "CCP Services"
  introMessage: Serices get checked every 5 Minutes. Notifications on downtimes will be sent automatically to IT staff.
  theme: dark
  favicon: https://raw.githubusercontent.com/ccp-eva/ccp-favicon/main/favicon/192.png
  faviconSvg: https://raw.githubusercontent.com/ccp-eva/ccp-favicon/main/favicon/192.png
  navbar:
    - title: Status
      href: https://ccp-eva.github.io/uptime-monitor/
    - title: CCP Page
      href: https://www.eva.mpg.de/comparative-cultural-psychology/index/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
